services:
  - type: web
    name: spotify-ai-dj-backend
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
